---
output:
  html_document: 
    toc: true
    toc_float: true
---

### Why I Teach
I love to share my passion(s) with others. Education has been a cornerstone of my life and I strongly 
believe in giving back to the community. What's better than having a lightbulb moment after spending hours
thinking through a problem? Being able to create that same illumination within another student with 
a concise explanation.

### Experience
A listing of some of my past teaching experiences.

  - Lecturer for core, graduate level courses within the Institute for Computational and Mathematical Engineering.
    - Served as a Lecturer for 7+ years for [CME 211](https://github.com/CME211/notes#contents) and [CME 212](https://explorecourses.stanford.edu/search?q=cme+212&view=catalog&page=0&filter-coursestatus-Active=on&collapse=&academicYear=20212022).
    - Earned a "Best Lecturer" award 3 different years! Awarded is determined and presented by students and faculty.
  
  - Teaching Assistant (CME 106, CME 323)
  
  - Teaching Fellow (CME 211, [CME 305 for which I authored lecture notes](http://stanford.edu/~rezab/classes/cme305/W17/305.pdf), as well as [authored the first set of thorough lecture notes for CME 323](https://stanford.edu/~rezab/classes/cme323/S17/))
  
  - [Fundamentals of Data Science Summer Workshops](https://icme.stanford.edu/events/icme-summer-workshops).
    - [Intro to R](https://asantucci.github.io/ICME-R-Programming-Workshop) '16, '17, '18, '19, '20, '21, '22,
    - [Intro to Python](https://asantucci.github.io/Python-programming-workshop/) '21, '22, and
    - Intro to Stats '17

#### Sample Materials
I enjoy consolidating information into concise and digestable notes. For example, here's a course summary from my 
[first statistical inference course](files/stats_200_cs.pdf). Some more examples:

  - I recently put together a few notes on an [Introduction to R Programming](files/intro_r.pdf) for a one-day short course.

  - Here's an example of some [distributed algorithms notes](files/cme323_lec5.pdf) I created for a course I helped teach. 
